### ISSUE TITLE
Threading issue

### ISSUE THREAD

**Issue by rbt** [atroxaper/p6-LogP6#2]
I think setup of the writer needs to be protected by a lock.

This exception appears periodically in the code below it on 2020.02.1
```
LogP6 error: X::AdHoc: This continuation has already been invoked
  in method show at /home/rbt/.rakudobrew/versions/moar-2020.02.1/install/share/perl6/site/sources/32F6080E8249F62DC3D3B7C82A94ACDEE1CDF97D (LogP6::WriterConf::Pattern) line 143
  in method show at /home/rbt/.rakudobrew/versions/moar-2020.02.1/install/share/perl6/site/sources/32F6080E8249F62DC3D3B7C82A94ACDEE1CDF97D (LogP6::WriterConf::Pattern) line 112
  in method write at /home/rbt/.rakudobrew/versions/moar-2020.02.1/install/share/perl6/site/sources/39A5B25C8E39A625E7A477685C38186826012DAC (LogP6::Writer::Std) line 16
  in submethod log at /home/rbt/.rakudobrew/versions/moar-2020.02.1/install/share/perl6/site/sources/2C42F3AEF57D38CDE1B118476684360EF109C1B3 (LogP6::LoggerPure) line 153
  in method info at /home/rbt/.rakudobrew/versions/moar-2020.02.1/install/share/perl6/site/sources/2C42F3AEF57D38CDE1B118476684360EF109C1B3 (LogP6::LoggerPure) line 111
  in block  at /tmp/k.raku line 31
```

```
#!/usr/bin/env rakudo

use v6.d;

use LogP6 :configure;
need LogP6::LoggerPure;

# Output to Stderr
my $pattern = '%color{TRACE=yellow DEBUG=green INFO=blue WARN=magenta ERROR=red} %date{$yyyy-$MM-$dd $hh:$mm:$ss:$mss} t#%tid %level{WARN=W DEBUG=D ERROR=E TRACE=T INFO=I length=1} %trait - %msg';

my $groves = ( writer(:$pattern, :handle($*ERR)), filter(:level($debug)) );

cliche(
    :name<cl>,
    :matcher<audit>,
    grooves => $groves
);


my \log = get-logger('audit');

# Start execution threads
my @foo;
for 0 .. 100 {
    my $p = start {
        log.info('Start Worker');
    }
    @foo.push($p);
}

await Promise.allof(@foo);
```

I've also seen this exception which I assume is the same problem with different timing.
```
 2020-04-04 12:36::777 t#6 I audit - Start Worker
Use of uninitialized value of type Mu in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/rbt/.rakudobrew/versions/moar-2020.02.1/install/share/perl6/site/sources/32F6080E8249F62DC3D3B7C82A94ACDEE1CDF97D (LogP6::WriterConf::Pattern) line 112
Use of uninitialized value of type Mu in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
```

**Comment by atroxaper** [comment]
Hi, @rbt 
I'm so sorry for the late reaction. I don't know how to configure GitHub to notify me about issues only in my repos.

I've fixed the issue. See https://github.com/atroxaper/p6-LogP6/commit/9e51ab7e8ddb742a403444cc89a08cbad56dcfee if you are interested. The new version (1.6.2) will be available to install via zef soon today.

Thank you for your issue and interest in LogP6.

**Comment by rbt** [comment]
Oh. Interesting issue. I didn't realize lazy stuff wasn't thread safe.

You don't necessarily need to spell out the entire set though, adding .eager() ought to be sufficient.

**Comment by atroxaper** [comment]
Oh. Thank you for pointing me on .eager(). I’ll do so in the next versions :)

Are you using LogP6? Do you have some thoughts about it to share?

**Comment by rbt** [comment]
I do but only in a basic way, to change the log style based on environment.

```
use LogP6::WriterConf::StackDriver;

# Output to Stderr
my $pattern = '%color{TRACE=yellow DEBUG=green INFO=blue WARN=magenta ERROR=red} %date{$yyyy-$MM-$dd $hh:$mm:$ss:$mss} t#%tid %level{WARN=W DEBUG=D ERROR=E TRACE=T INFO=I length=1} %trait - %msg';

my $groves;
my $environment = %*ENV<EXECUTION_ENVIRONMENT> // q{development};
if $environment eq 'development' {
    # create anonymous writer and filter configuration
    $groves = ( writer(:$pattern, :handle($*ERR)), filter(:level($debug)) );
} else {
    my $sd = LogP6::WriterConf::StackDriver.new(:handle($*ERR), :name<audit>);
    $groves = ( writer($sd), filter(:level($debug)) );
}

cliche(
    :name<cl>,
    :matcher<audit>,
    grooves => $groves
);
```

**Comment by atroxaper** [comment]
One of the main ideas of LogP6 was decoupling log configuration and log using. That is why there is an option to use a file to configure a logger. For your case, it may do something like the following:

1. save `./log-p6.json` (default filename and path) file with content:
```
{
    "writers": [{
        "type": "custom",
        "require": "LogP6::WriterConf::StackDriver",
        "fqn-class": "LogP6::WriterConf::StackDriver",
        "args": {
            "name": "audit"
        }}],
    "filters": [{ "type": "std", "name": "audit", "level": "debug" }],
    "cliches": [{
        "name": "cl",
        "matcher": "audit",
        "grooves": [ "audit", "audit" ],
        "default-handle": { "type": "std", "path": "err" }
        }]
  }
```
2. save `log-p6-dev.json` file somewhere with content:
```
{
    "writers": [{
        "type": "std",
        "name": "audit",
        "pattern": "%color{TRACE=yellow DEBUG=green INFO=blue WARN=magenta ERROR=red} %date{$yyyy-$MM-$dd $hh:$mm:$ss:$mss} t#%tid %level{WARN=W DEBUG=D ERROR=E TRACE=T INFO=I length=1} %trait - %msg"
        }],
    "filters": [{ "type": "std", "name": "audit", "level": "debug" }],
    "cliches": [{
        "name": "cl",
        "matcher": "audit",
        "grooves": [ "audit", "audit" ],
        "default-handle": { "type": "std", "path": "err", "out-buffer": false },
        "wrapper": { "type": "each" }
        }]
  }
```

3. in your code leave only:
```
use LogP6;
my \log = get-logger('audit');
```
4. for development purpose, specify `LOG_P6_JSON` environment variable as a path to `log-p6-dev.json`

Then you may change a log configuration without touching the code and, even, on the fly in development mode (thanks to the `wrapper` section in the `cliche`).

Also, if there is not so convenient to specify `LOG_P6_JSON` for each program being developed, then you may:

* specify `LOG_P6_JSON` in the code:
```
use LogP6 :configure;
%*ENV<LOG_P6_JSON> = './log-p6-dev.json' if 'development' eq %*ENV<EXECUTION_ENVIRONMENT>;
```
* or directly initialize `LogP6` from the configuration file:
```
use LogP6 :configure;
init-from-file('./log-p6-dev.json') if 'development' eq %*ENV<EXECUTION_ENVIRONMENT>;
```
In the last case, you need to add `config-path` field to the `wrapper` section with `log-p6-dev.json` path as value.

**Comment by rbt** [comment]
> One of the main ideas of LogP6 was decoupling log configuration and log using.

Yeah, I understand that and before Kubernetes that's exactly what I would have done so the sysadmins could muck with logging after deployment without needing to involve a developer.

Now I would need to make the helm chart dynamic to generate a different config file based on the target envrionment, then load that into a configmap, and after all that it's still hard-wired logic that sits in a git repo but now in several locations instead of a single Class that gets inherited as needed.

**Comment by atroxaper** [comment]
I see, good point 🤔
